require 'rake/clean'

GENERATED_TEMPLATES = FileList['*.haml'].ext('html')
GENERATED_STYLESHEETS = FileList['*.sass'].ext('css')

CLOBBER.include(GENERATED_TEMPLATES)
CLOBBER.include(GENERATED_STYLESHEETS)

rule '.html' => ['.haml'] do |t|
  sh "haml #{t.source} #{t.name}"
end

rule '.css' => ['.sass'] do |t|
  sh "sass --style expanded #{t.source} #{t.name}"
end

namespace :templates do
  desc 'generate html templates from haml'
  task :generate => GENERATED_TEMPLATES
end

namespace :stylesheets do
  desc 'generate css stylesheets from sass'
  task :generate => GENERATED_STYLESHEETS
end

desc 'generate all'
task :generate => ['stylesheets:generate', 'templates:generate']
